[package]
name = "zeroid_rust_passport_utils"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib", "staticlib"]
name = "zeroid_rust_passport_utils"
 
[dependencies]
uniffi = { version = "0.25.3", features = [ "cli" ] }